"""Shared constant sets and dictionaries for parsing helpers."""

from __future__ import annotations

FLUID_UNITS = {
    "l",
    "liter",
    "liters",
    "ml",
    "milliliter",
    "fl_oz",
    "fluid_ounce",
    "cup",
    "cups",
    "tablespoon",
    "tablespoons",
    "tbsp",
    "teaspoon",
    "teaspoons",
    "tsp",
    "quart",
    "quarts",
    "pint",
    "pints",
    "gallon",
    "gallons",
}

WEIGHT_UNITS = {
    "lbs",
    "lb",
    "pound",
    "pounds",
    "oz",
    "ounce",
    "ounces",
    "kg",
    "kilogram",
    "g",
    "gram",
    "grams",
}

COUNT_UNITS = {
    "bunch",
    "head",
    "package",
    "pkg",
    "bag",
    "bags",
    "box",
    "boxes",
    "can",
    "cans",
    "jar",
    "jars",
    "bottle",
    "bottles",
    "loaf",
    "loaves",
    "dozen",
    "count",
    "pack",
    "packs",
    "clove",
    "cloves",
    "slice",
    "slices",
    "piece",
    "pieces",
    "stick",
    "sticks",
}

ALL_UNITS = WEIGHT_UNITS | FLUID_UNITS | COUNT_UNITS

NUMBER_WORDS = {
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "fifteen",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
    "twenty",
    "thirty",
    "forty",
    "fifty",
    "sixty",
    "seventy",
    "eighty",
    "ninety",
    "hundred",
    "dozen",
}

STOP_WORDS = {"of", "and"}

IRREGULAR_PLURALS = {
    "teeth": "tooth",
    "geese": "goose",
    "feet": "foot",
    "men": "man",
    "women": "woman",
    "children": "child",
    "mice": "mouse",
    "lice": "louse",
    "oxen": "ox",
    "thighs": "thigh",
    "knives": "knife",
    "wives": "wife",
    "lives": "life",
    "leaves": "leaf",
    "wolves": "wolf",
    "shelves": "shelf",
    "selves": "self",
    "scarves": "scarf",
    "staves": "stave",
    "cacti": "cactus",
    "fungi": "fungus",
    "foci": "focus",
    "nuclei": "nucleus",
    "syllabi": "syllabus",
    "alumni": "alumnus",
    "bacteria": "bacterium",
    "data": "datum",
    "media": "medium",
    "analyses": "analysis",
    "diagnoses": "diagnosis",
    "parentheses": "parenthesis",
    "theses": "thesis",
    "indices": "index",
    "matrices": "matrix",
    "vertices": "vertex",
    "radii": "radius",
    "appendices": "appendix",
    "loaves": "loaf",
    "potatoes": "potato",
    "tomatoes": "tomato",
    "heroes": "hero",
    "echoes": "echo",
    "halves": "half",
    "calves": "calf",
    "hooves": "hoof",
    "torpedoes": "torpedo",
    "mosquitoes": "mosquito",
    "zeroes": "zero",
    "axes": "axis",
    "dice": "die",
    "people": "person",
}

UNIT_MAPPING = {
    "lbs": "pound",
    "lb": "pound",
    "pound": "pound",
    "pounds": "pound",
    "oz": "ounce",
    "ounce": "ounce",
    "ounces": "ounce",
    "kg": "kilogram",
    "kilogram": "kilogram",
    "g": "gram",
    "gram": "gram",
    "grams": "gram",
    "l": "liter",
    "liter": "liter",
    "liters": "liter",
    "ml": "milliliter",
    "milliliter": "milliliter",
    "fl_oz": "fluid_ounce",
    "fluid_ounce": "fluid_ounce",
    "cup": "cup",
    "cups": "cup",
    "tablespoon": "tablespoon",
    "tablespoons": "tablespoon",
    "tbsp": "tablespoon",
    "teaspoon": "teaspoon",
    "teaspoons": "teaspoon",
    "tsp": "teaspoon",
    "quart": "quart",
    "quarts": "quart",
    "pint": "pint",
    "pints": "pint",
    "gallon": "gallon",
    "gallons": "gallon",
}

__all__ = [
    "FLUID_UNITS",
    "WEIGHT_UNITS",
    "COUNT_UNITS",
    "ALL_UNITS",
    "NUMBER_WORDS",
    "STOP_WORDS",
    "IRREGULAR_PLURALS",
    "UNIT_MAPPING",
]

