"""intial db migration"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import geoalchemy2
from pgvector.sqlalchemy import Vector
import sqlmodel


revision = '431cc1f9b84f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pkg_qty_value', sa.Float(), nullable=True),
    sa.Column('pkg_qty_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_qty_value', sa.Float(), nullable=True),
    sa.Column('base_qty_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_client_id'), 'shopping_lists', ['client_id'], unique=True, if_not_exists=True)
    op.create_table('store_chains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text_qty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_text_item', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty_value', sa.Float(), nullable=False),
    sa.Column('qty_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('norm_qty_value', sa.Float(), nullable=False),
    sa.Column('norm_qty_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_items_list_id'), 'list_items', ['list_id'], unique=False, if_not_exists=True)
    op.create_index('ix_list_items_list_id_position', 'list_items', ['list_id', 'position'], unique=False, if_not_exists=True)
    op.create_table('route_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('client_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opt_mode', sa.Enum('PRICE', 'BALANCED', 'SPEED', name='optimizationmode'), nullable=False),
    sa.Column('lowest_unit_price', sa.Boolean(), nullable=False),
    sa.Column('max_stores', sa.Integer(), nullable=False),
    sa.Column('user_latitude', sa.Float(), nullable=True),
    sa.Column('user_longitude', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_distance_m', sa.Integer(), nullable=True),
    sa.Column('total_travel_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_plans_client_token'), 'route_plans', ['client_token'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_route_plans_list_id'), 'route_plans', ['list_id'], unique=False, if_not_exists=True)
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('chain_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hours_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geography', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['store_chains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stores_geography', 'stores', ['geography'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_stores_chain_id'), 'stores', ['chain_id'], unique=False, if_not_exists=True)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('MATCH', 'PRICING', 'OPTIMIZE', name='jobstage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['route_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'stage', name='uq_jobs_plan_stage')
    )
    op.create_index(op.f('ix_jobs_plan_id'), 'jobs', ['plan_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_jobs_task_id'), 'jobs', ['task_id'], unique=False, if_not_exists=True)
    op.create_table('plan_selected_stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['route_plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'store_id', name='uq_plan_selected_stores_plan_store')
    )
    op.create_index(op.f('ix_plan_selected_stores_plan_id'), 'plan_selected_stores', ['plan_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_plan_selected_stores_store_id'), 'plan_selected_stores', ['store_id'], unique=False, if_not_exists=True)
    op.create_table('plan_store_visits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('travel_sec_from_prev', sa.Integer(), nullable=True),
    sa.Column('distance_m_from_prev', sa.Integer(), nullable=True),
    sa.Column('subtotal_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['route_plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'sequence', name='uq_plan_store_visits_plan_sequence')
    )
    op.create_index(op.f('ix_plan_store_visits_plan_id'), 'plan_store_visits', ['plan_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_plan_store_visits_store_id'), 'plan_store_visits', ['store_id'], unique=False, if_not_exists=True)
    op.create_table('store_products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('external_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aisle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shelf_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'external_sku', name='uq_store_products_store_sku'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_store_products_store_product')
    )
    op.create_index(op.f('ix_store_products_product_id'), 'store_products', ['product_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_store_products_store_id'), 'store_products', ['store_id'], unique=False, if_not_exists=True)
    op.create_table('price_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_product_id', sa.Uuid(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('unit_price_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_entries_store_product_fetched_at', 'price_entries', ['store_product_id', 'fetched_at'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_price_entries_store_product_id'), 'price_entries', ['store_product_id'], unique=False, if_not_exists=True)
    op.create_index('ix_price_entries_store_product_is_current', 'price_entries', ['store_product_id', 'is_current'], unique=False, if_not_exists=True)
    op.create_table('item_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('list_item_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('chosen_store_product_id', sa.Uuid(), nullable=True),
    sa.Column('chosen_price_entry_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SELECTED', 'REJECTED', 'UNMATCHED', name='matchstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by_user', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chosen_price_entry_id'], ['price_entries.id'], ),
    sa.ForeignKeyConstraint(['chosen_store_product_id'], ['store_products.id'], ),
    sa.ForeignKeyConstraint(['list_item_id'], ['list_items.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['route_plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'list_item_id', 'store_id', name='uq_item_matches_plan_item_store')
    )
    op.create_index(op.f('ix_item_matches_chosen_price_entry_id'), 'item_matches', ['chosen_price_entry_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_item_matches_chosen_store_product_id'), 'item_matches', ['chosen_store_product_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_item_matches_list_item_id'), 'item_matches', ['list_item_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_item_matches_plan_id'), 'item_matches', ['plan_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_item_matches_store_id'), 'item_matches', ['store_id'], unique=False, if_not_exists=True)
    op.create_table('plan_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('plan_store_visit_id', sa.Uuid(), nullable=False),
    sa.Column('list_item_id', sa.Uuid(), nullable=False),
    sa.Column('store_product_id', sa.Uuid(), nullable=True),
    sa.Column('price_entry_id', sa.Uuid(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('per_qty_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extended_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_item_id'], ['list_items.id'], ),
    sa.ForeignKeyConstraint(['plan_store_visit_id'], ['plan_store_visits.id'], ),
    sa.ForeignKeyConstraint(['price_entry_id'], ['price_entries.id'], ),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_items_list_item_id'), 'plan_items', ['list_item_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_plan_items_plan_store_visit_id'), 'plan_items', ['plan_store_visit_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_plan_items_price_entry_id'), 'plan_items', ['price_entry_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_plan_items_store_product_id'), 'plan_items', ['store_product_id'], unique=False, if_not_exists=True)
    op.create_table('item_match_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('item_match_id', sa.Uuid(), nullable=False),
    sa.Column('store_product_id', sa.Uuid(), nullable=False),
    sa.Column('price_entry_id', sa.Uuid(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rejected_by_user', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_match_id'], ['item_matches.id'], ),
    sa.ForeignKeyConstraint(['price_entry_id'], ['price_entries.id'], ),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_match_id', 'rank', name='uq_item_match_candidates_match_rank')
    )
    op.create_index(op.f('ix_item_match_candidates_item_match_id'), 'item_match_candidates', ['item_match_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_item_match_candidates_price_entry_id'), 'item_match_candidates', ['price_entry_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_item_match_candidates_store_product_id'), 'item_match_candidates', ['store_product_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_match_candidates_store_product_id'), table_name='item_match_candidates', if_exists=True)
    op.drop_index(op.f('ix_item_match_candidates_price_entry_id'), table_name='item_match_candidates', if_exists=True)
    op.drop_index(op.f('ix_item_match_candidates_item_match_id'), table_name='item_match_candidates', if_exists=True)
    op.drop_table('item_match_candidates')
    op.drop_index(op.f('ix_plan_items_store_product_id'), table_name='plan_items', if_exists=True)
    op.drop_index(op.f('ix_plan_items_price_entry_id'), table_name='plan_items', if_exists=True)
    op.drop_index(op.f('ix_plan_items_plan_store_visit_id'), table_name='plan_items', if_exists=True)
    op.drop_index(op.f('ix_plan_items_list_item_id'), table_name='plan_items', if_exists=True)
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_item_matches_store_id'), table_name='item_matches', if_exists=True)
    op.drop_index(op.f('ix_item_matches_plan_id'), table_name='item_matches', if_exists=True)
    op.drop_index(op.f('ix_item_matches_list_item_id'), table_name='item_matches', if_exists=True)
    op.drop_index(op.f('ix_item_matches_chosen_store_product_id'), table_name='item_matches', if_exists=True)
    op.drop_index(op.f('ix_item_matches_chosen_price_entry_id'), table_name='item_matches', if_exists=True)
    op.drop_table('item_matches')
    op.drop_index('ix_price_entries_store_product_is_current', table_name='price_entries', if_exists=True)
    op.drop_index(op.f('ix_price_entries_store_product_id'), table_name='price_entries', if_exists=True)
    op.drop_index('ix_price_entries_store_product_fetched_at', table_name='price_entries', if_exists=True)
    op.drop_table('price_entries')
    op.drop_index(op.f('ix_store_products_store_id'), table_name='store_products', if_exists=True)
    op.drop_index(op.f('ix_store_products_product_id'), table_name='store_products', if_exists=True)
    op.drop_table('store_products')
    op.drop_index(op.f('ix_plan_store_visits_store_id'), table_name='plan_store_visits', if_exists=True)
    op.drop_index(op.f('ix_plan_store_visits_plan_id'), table_name='plan_store_visits', if_exists=True)
    op.drop_table('plan_store_visits')
    op.drop_index(op.f('ix_plan_selected_stores_store_id'), table_name='plan_selected_stores', if_exists=True)
    op.drop_index(op.f('ix_plan_selected_stores_plan_id'), table_name='plan_selected_stores', if_exists=True)
    op.drop_table('plan_selected_stores')
    op.drop_index(op.f('ix_jobs_task_id'), table_name='jobs', if_exists=True)
    op.drop_index(op.f('ix_jobs_plan_id'), table_name='jobs', if_exists=True)
    op.drop_table('jobs')
    op.drop_index(op.f('ix_stores_chain_id'), table_name='stores', if_exists=True)
    op.drop_index('idx_stores_geography', table_name='stores', postgresql_using='gist', if_exists=True)
    op.drop_table('stores')
    op.drop_index(op.f('ix_route_plans_list_id'), table_name='route_plans', if_exists=True)
    op.drop_index(op.f('ix_route_plans_client_token'), table_name='route_plans', if_exists=True)
    op.drop_table('route_plans')
    op.drop_index('ix_list_items_list_id_position', table_name='list_items', if_exists=True)
    op.drop_index(op.f('ix_list_items_list_id'), table_name='list_items', if_exists=True)
    op.drop_table('list_items')
    op.drop_table('store_chains')
    op.drop_index(op.f('ix_shopping_lists_client_id'), table_name='shopping_lists', if_exists=True)
    op.drop_table('shopping_lists')
    op.drop_table('products')
    # ### end Alembic commands ###
