"""update job"""

from alembic import op
import sqlalchemy as sa



revision = '70140a24605c'
down_revision = '38431d81db08'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'task_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'task_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
