"""add cascade delete to item_match_candidate_id foreign key"""

from alembic import op
import sqlalchemy as sa



revision = '7a174e9b2a16'
down_revision = 'd2e8e7b8da2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_matches_item_match_candidate_id_fkey'), 'item_matches', type_='foreignkey')
    op.create_foreign_key(None, 'item_matches', 'item_match_candidates', ['item_match_candidate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_matches', type_='foreignkey')
    op.create_foreign_key(op.f('item_matches_item_match_candidate_id_fkey'), 'item_matches', 'item_match_candidates', ['item_match_candidate_id'], ['id'])
    # ### end Alembic commands ###
