"""minor change"""

from alembic import op
import sqlalchemy as sa



revision = 'be33456893b7'
down_revision = '431cc1f9b84f'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_lists_client_id'), table_name='shopping_lists')
    op.create_index(op.f('ix_shopping_lists_client_id'), 'shopping_lists', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_lists_client_id'), table_name='shopping_lists')
    op.create_index(op.f('ix_shopping_lists_client_id'), 'shopping_lists', ['client_id'], unique=True)
    # ### end Alembic commands ###
